### ISSUE TITLE
Matplotlib/first_part : переносимость кода

### ISSUE THREAD

**Issue by avasyukov** [Sageblatt/MIPT_Labs#1]
(Этого не было в материалах. И это почти офтоп. Но тем не менее.)

Вот эта строчка:
https://github.com/Sageblatt/MIPT_Labs/blob/69a784eed892ea39e87a7aaaac77c4d3a98b572c/Matplotlib/first_part/first_part.py#L5

внезапно не переносима между разными операционными системами.

Потому что разделитель элементов пути по ФС разный в разных ОС. Идейно верно склеить кусочки пути (имя папки и имя файла) с помощью os.path.join.

Upd: ну и чтобы два раза не вставать - файл таки надо закрыть после чтения.

**Comment by Sageblatt** [comment]
[Пофикшено.](https://github.com/Sageblatt/MIPT_Labs/commit/5ea55ba783ed21d544b2be5c0fa52c30256d02f9)

**Comment by avasyukov** [comment]
Да, так стало совсем хорошо.
