### ISSUE TITLE
pandas / second_part : рисование

### ISSUE THREAD

**Issue by avasyukov** [Sageblatt/MIPT_Labs#2]
Не ошибка. Но вот это всё:
https://github.com/Sageblatt/MIPT_Labs/blob/f660b872ce3634fdf6051422def473af450c3c7e/Pandas/second_part/second.py#L19-L26
можно нарисовать средствами pandas-ов, будет значительно короче.

Примерно вот так: `(pandas-овый объект).plot(kind='bar', ax=ax[0], title="Number of flights")`. И промежуточные переменные в `data` тоже станут не нужны.

**Comment by Sageblatt** [comment]
[Исправлено этим коммитом.](https://github.com/Sageblatt/MIPT_Labs/commit/efc7693a09908977d47102bd792758eb623841ae)
