### ISSUE TITLE
pandas / third_part : рисование

### ISSUE THREAD

**Issue by avasyukov** [Sageblatt/MIPT_Labs#3]
Аналогично прошлому эпизоду. Вот это всё можно заменить pandas-овыми методами:
https://github.com/Sageblatt/MIPT_Labs/blob/f660b872ce3634fdf6051422def473af450c3c7e/Pandas/third_part/third.py#L22-L28

Заодно станут не нужны промежуточные `names, f_stat, o_stat, data`, которые несколько снижают красоту кода.

**Comment by Sageblatt** [comment]
[Исправлено этим коммитом.](https://github.com/Sageblatt/MIPT_Labs/commit/efc7693a09908977d47102bd792758eb623841ae)
