### ISSUE TITLE
pandas / third_part : лишняя операция

### ISSUE THREAD

**Issue by avasyukov** [Sageblatt/MIPT_Labs#4]
Мелочь, но всё же. Вот эта операция не несёт смысла:
https://github.com/Sageblatt/MIPT_Labs/blob/f660b872ce3634fdf6051422def473af450c3c7e/Pandas/third_part/third.py#L6

Сама по себе она понятна. Но `merge` сам вычеркнет лишние строки. А `names` станут не нужны, если рисовать средствами pandas-ов уже готовые данные.

**Comment by Sageblatt** [comment]
[Исправлено этим коммитом.](https://github.com/Sageblatt/MIPT_Labs/commit/efc7693a09908977d47102bd792758eb623841ae)
